apiVersion: v1
kind: Pod
metadata:
  name: business-app
  labels:
    name: business-app
spec:
  initContainers:
    - name: configurer
      image: busybox:1.32.0
      command:
        - 'sh'
        - '-c'
        - 'echo Configuring application... && mkdir -p /usr/shared/app && echo -e "{\"dbConfig\":{\"host\":\"localhost\",\"port\":5432,\"dbName\":\"customers\"}}" > /usr/shared/app/config.json'
        - 'cat /usr/shared/app/config.json'
      volumeMounts:
        - mountPath: "/usr/shared/app"
          name: configdir
  containers:
  - name: web
    image: bmuschko/nodejs-read-config:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    volumeMounts:
      - mountPath: "/usr/shared/app"
        name: configdir
  volumes:
    - name: configdir
      emptyDir: {}
        