apiVersion: v1
kind: Pod
metadata:
  name: complex-pod
  labels:
    name: complex-pod
spec:
  initContainers:
    - name: setup
      image: busybox
      command:
        - "sh"
        - "-c"
        - "wget -O- google.com"
  containers:
  - name: app
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
