apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
  labels:
    name: liveness-pod
spec:
  containers:
  - name: app
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    args:
      - "/bin/sh"
      - "-c"
      - "while true; do touch /tmp/heartbeat.txt; sleep 5; done;"
    livenessProbe:
      exec:
        command:
          - "test 'find /tmp/heartbeat.txt -mmin -1'"
      initialDelaySeconds: 5
      periodSeconds: 30
