apiVersion: v1
kind: Pod
metadata:
  name: custom-cmd
  labels:
    name: custom-cmd
spec:
  containers:
  - name: myapp
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - "sh"
      - "-c"
      - "top-analyzer --all"
