apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    name: web-server
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    startupProbe:
      httpGet:
        path: /
        port: myapp-port
    readinessProbe:
      httpGet:
        path: /
        port: myapp-port
      initialDelaySeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: myapp-port
      initialDelaySeconds: 10
      periodSeconds: 30
        
    ports:
      - containerPort: 80
        name: myapp-port
