apiVersion: v1
kind: Pod
metadata:
  name: configured-pod
  labels:
    name: configured-pod
spec:
  containers:
  - name: app
    image: nginx:1.19.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /etc/config
        name: config-volume
  volumes:
    - name: config-volume
      configMap:
        name: backend-config
