apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: project-firebird
  labels:
    name: myapp
spec:
  serviceAccountName: monitoring
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128m"
        cpu: "1"

    ports:
      - containerPort: 8080

