apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
  labels:
    name: readiness-pod
spec:
  containers:
  - name: hello-world
    image: bmuschko/nodejs-hello-world:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
        name: nodejs-port
    readinessProbe:
      httpGet:
        path: /
        port: nodejs-port
      initialDelaySeconds: 2
      periodSeconds: 8
