apiVersion: v1
kind: Pod
metadata:
  name: consumer
  labels:
    name: consumer
spec:
  containers:
  - name: app
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /var/app
        name: app-secret-vol
        readOnly: true
  volumes:
    - name: app-secret-vol
      secret: 
       secretName: ext-service-secret
        
