apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  labels:
    name: security-context-demo
spec:
  containers:
  - name: myapp
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    securityContext:
      capabilities:
        add:
          - "SYS_TIME"
  restartPolicy: Never
